### ISSUE TITLE
请问这个问题可以解决吗：ios手机端，不能随意顺序地显示挖空

### ISSUE THREAD

**Issue by didqls** [ruin1990/AnkiTemplate#2]
比如，一张卡片里，一句话挖空了第1  第2  第3  第4  个词，但是手机端只能通过按钮1234这样按顺序的显示，隐藏也只能按顺序。做不到想点哪个点哪个。这个问题能解决吗~ 谢谢~

**Comment by ruin1990** [comment]
虽然大概知道你的意思，不过你应该没测试过我这ClozeAdv卡组吧，之前有找ios的朋友测试过的。
如果还不行呢，请你提供使用我模版的卡组，我才方便帮你看下是啥问题。
另外呢，你可以参考一下我提供的示例卡组的制作方法，你应该没有看anki官方的cloze教程才会有此疑惑，这部分内容不应该在这里讨论，推荐你直接去anki交流群问一下，了解下c1，c2，...，cn的本质实现
