### ISSUE TITLE
your apkg contains a 15digit card id which can cause some problems

### ISSUE THREAD

**Issue by ijgnd** [ruin1990/AnkiTemplate#3]
Thanks for sharing the ClozeAdv note type with your deck [ClozeAdv ( Cloze Advance )](https://ankiweb.net/shared/info/457099967). The same deck is also in this repo at https://github.com/ruin1990/AnkiTemplate/blob/main/ClozeAdv/AnkiTemplate_ClozeAdv.apkg

This shared deck has two cards that have 15 digit card ids (cids). Usually card ids (cids) are only 13 digits.

As far as I see Anki and Ankidroid assume that card ids are 13 digits. The 13 digit string is the creation time of the card in epoch time in milliseconds. So cids made by Anki will be 13 digits for the coming two centuries.

card ids that consist of 15 digits seem to be produced by some buggy external tools according to the anki creator, [source](https://forums.ankiweb.net/t/bug-does-anyone-know-why-some-of-my-card-id-have-changed-to-15-digits/6471/2).

I had the problem that this card always shows up when searching with `added:1`. [here's](https://github.com/ankidroid/Anki-Android/issues/8012) another 15digit card id bug (that's not caused by cards not from your deck). But as far as I understand your card might create a similar problem.

You can check for yourself with the add-on [Advanced Browser](https://ankiweb.net/shared/info/874215009) after having changed the add-on setting `"Show internal fields"` to true. I double check with "DB Browser for SQLite".

I suggest to recreate this deck and update the ankiweb listing.

**Comment by ruin1990** [comment]
Thank you for your feedback, I am sorry for not replying to you in time due to work matters recently.
According to my test, if a Note contains multiple Cards in the Cloze template, the cards other than Cloze1 will change from 13-digit cid to 15-digit cid. I have tested this card group on AnkiDroid, AnkiWindows, and AnkiMobile. It can be used normally, and the card is not hidden (of course it should not be the latest version, it should be the 21 year version)
Secondly, I think I mainly provide templates, which have nothing to do with Deck itself. Anyway, users can use my templates to create new cards after importing.

**Comment by ijgnd** [comment]
Thank you very much for taking the time to investigate this. Also to make it clear: I'm very grateful that you are sharing your work for free.

&nbsp;

Your comment made me unsure. So I downloaded the latest Anki desktop version 2.1.55 and made a new profile and ran it without any add-ons. I imported your deck downloaded from https://ankiweb.net/shared/info/457099967

Now I get the following message during import:

> This deck contains timestamps in the future. Please contact the deck author and ask them to fix the issue.

Then nothing is imported: no note and also no note type. So your deck is broken in 2.1.55.

This is new behavior. The prior Anki version 2.1.54 from the summer imported the deck. 

I think this change was motivated by this: https://forums.ankiweb.net/t/issue-with-huge-card-ids/12165 . 

&nbsp;

Fixing this is simple: You create new notes inside anki, delete the old notes (which automaically deletes the cards that anki makes from the notes) and export this deck. This should take less than 5 minutes.

&nbsp;

Even if you don't like 2.1.55. I'd advocate for fixing this for older Anki versions.

you wrote:

>  I have tested this card group on AnkiDroid, AnkiWindows, and AnkiMobile. It can be used normally, and the card is not hidden 

That's also my observation: *in general* in works but a huge timestamp can lead to strange problems in corner cases.

> I think I mainly provide templates, which have nothing to do with Deck itself.

Technically you can't provide just the templates you always provide a note and each note must have at least one card that anki generates by using your templates.

> Anyway, users can use my templates to create new cards after importing.

That's true. You can delete the bundled note. But my impression is that many people won't do that. Having broken card ids might lead people to blame other add-ons for causing problems. As I said I had time consuming discussions with people who had 15-digit card-ids where my add-ons didn't work.

&nbsp;

&nbsp;

My main point is: It's great that you share your work. I think you've done 99% of the work.

I just think you have a problem that's very quick to fix (that for new users on 2.1.55 unforunately ruins all your hard work).

**Comment by ruin1990** [comment]
Oh, has it been upgraded to 2.1.55? 
Actually, I still using 2.1.49, No wonder I haven't been prompted for this problem.
I probably know what happened. 
Thank you for your detailed answer.👍👍👍 I think I can update it.

PS: I'm sorry that I can only watch github once every time for such a long time to follow up this issue.

**Comment by ruin1990** [comment]
I'm really sorry because I haven't passed an exam and I didn't dare to upgrade Anki randomly to avoid using the decks on other devices. (Yes, I have been taking the exam for 3 years. T_T) I will update this after I pass the exam. Because I saw someone on ankiweb saying there was a bug, but I didn’t know what the specific bug was and couldn’t reproduce it, so I thought of solving it together before updating.

**Comment by ruin1990** [comment]
I think I know where the problem is. I used the latest version of Anki and it seems that the problem has been solved. I will update it together after I fix other problems.
