### ISSUE TITLE
Some clozer not revealing in new versions of anki.

### ISSUE THREAD

**Issue by huandney** [ruin1990/AnkiTemplate#4]
Hello how long,
I have been using your script for a long time perfectly, but in the new versions of anki I am having random problems when revealing some cards, for example:
```
{{c1::test1}}
{{c2::test2}}
{{c3::test3}}
{{c3::test3}}
{{c4::test4}}
```
or
```
{{c1::test1}}
{{c2::test2}}
{{c3::test3}}
{{c4::test4}}
{{c4::test4}}
```
As we can see below:
![Recording 2023-04-03 at 20 15 51](https://user-images.githubusercontent.com/19948348/229655092-35117743-da8b-42ae-972c-87491e60c614.gif)

I saw with the AnkiWebview Inspector extension the following error in the console:

```
VM268:419 Uncaught TypeError: Cannot read properties of undefined (reading 'indexOf')
    at HTMLSpanElement.<anonymous> (<anonymous>:419:27)
    at Function.each (reviewer.js:1:3985)
    at u.fn.init.each (reviewer.js:1:2459)
    at add_answer_into_cloze (<anonymous>:414:14)
    at <anonymous>:480:1
    at reviewer.js:7:117257
    at new Promise (<anonymous>)
    at fl (reviewer.js:7:117002)
    at reviewer.js:7:117507
    at Generator.next (<anonymous>)
reviewer.js:7 Uncaught TypeError: Cannot read properties of null (reading 'style')
    at Ar (reviewer.js:7:112035)
```
Maybe it's something easy to fix, but I don't have enough knowledge.
Thanks a lot!

----
Edited:
I had not noticed another problem, when we have more than one cloze as below:
`{{c1::1}} {{c1::1}}  {{c2::2}} {{c2::2}} {{c3::3}} {{c3::3}} {{c4::4}} {{c4::4}}`
![Recording 2023-04-07 at 04 10 44](https://user-images.githubusercontent.com/19948348/230570419-a2fde25b-26c6-4d28-83f9-b2d8257410cf.gif)

**Comment by ruin1990** [comment]
emmm... what is your anki version and what is your platform ?
I think it maybe a issue with auto next card's code.

**Comment by ruin1990** [comment]
Could you please provide colpkg or apkg decks?

**Comment by ruin1990** [comment]
https://github.com/ruin1990/AnkiTemplate/blob/main/ClozeAdv/AnkiTemplate_ClozeAdv.apkg

You can test it
