### ISSUE TITLE
mathjax包裹错误

### ISSUE THREAD

**Issue by grantting** [ruin1990/AnkiTemplate#5]
例如：\(tany\dfrac{\sqrt{4}}{4T^{6}}\)，挖空后会显示[...]{4T^{6}}\)，点击后知识显示单纯的文本\(tany\dfrac{\sqrt{4{4T^{6}}\)}}

**Comment by ruin1990** [comment]
哦这个问题我忘记特别说明的，抱歉哈才看到

mathjax的文本中如果你有连续的{{或者}}，中间加空格就行了
以你的例子来说：
\( {{c1:: tany\dfrac{\sqrt{4} }{4T^{6} } }} \)
这里只要保证cloze的大括号才是连续的，公式里加**空格**就行了

**Comment by ruin1990** [comment]
我在 #7  做了详细的解答
另外还可以参考[ClozeAdv Mathjax 特殊处理指南](https://github.com/ruin1990/AnkiTemplate/tree/main/ClozeAdv#mathjax-bugs)
