### ISSUE TITLE
请问可以在模板里加入打字输入功能吗

### ISSUE THREAD

**Issue by pladymclan** [ruin1990/AnkiTemplate#6]
就是每一个填空都有一个对应的输入框可以打上答案？感觉这样可以更有助于记忆。
ps:很感谢你的模板，我找到的最好的填空题模板。很遗憾我并不会代码。

**Comment by ruin1990** [comment]
可以吧，但是这个不太实用啊，因为anki有个现成的模版就有这功能
你看看Anki自带的模版Basic(Type in answer)

**Comment by ruin1990** [comment]
另外欢迎PR
