### ISSUE TITLE
部分行间公式点击不显示答案，行内公式点击后Mathjax渲染失败

### ISSUE THREAD

**Issue by EchoingWhispers** [ruin1990/AnkiTemplate#7]
您好，很喜欢这个牌组模板，但使用过程中有一些小Bug，似乎不支持太复杂的数学公式。
比如部分行间公式点击不显示答案，行内公式点击后Mathjax渲染不成功。

挖空的公式例子如下

行间公式：
\begin{aligned}
&{{c1::{\color{#C72929}{\|f+g\|_p=\left(\int_E(f+g)\cdot(f+g)^*\right)^{1/p} } } }}\\
&=\left(\int_Ef\cdot(f+g)^*+\int_Eg\cdot(f+g)^*\right)^{1/p} \\
&\leq\|f\|_p\cdot\|(f+g)^*\|_q+\|g\|_p\cdot\|(f+g)^*\|_q \\
&=\|f\|_p+\|g\|_p
\end{aligned}

行内公式：
f(x)={{c1::{\color{#C72929}{ab{a\over b}2132313 } } }}

**Comment by EchoingWhispers** [comment]
[
![1](https://github.com/ruin1990/AnkiTemplate/assets/172566400/5e60bdd8-2082-4eeb-92ad-c24e33378874)
](url)

**Comment by EchoingWhispers** [comment]
![1](https://github.com/ruin1990/AnkiTemplate/assets/172566400/9b7373c7-3fef-4341-a95f-bd85e367a495)

**Comment by ruin1990** [comment]
这个问题我有思路了，非常抱歉哈

**Comment by ruin1990** [comment]
我大概发现了问题：
1.是公式内非cloze用到的大括号之间都加个空格，大概是下面这样
![image](https://github.com/user-attachments/assets/e0829254-76dc-4f2d-87cf-b382bfdafba1)
2.似乎对于纯mathjax的cloze格式处理有点问题或者是mathjax的重新渲染机制出了问题，有待验证

**Comment by ruin1990** [comment]
我大概找到了问题，目前我整套思路强依赖于整行的正则匹配，因此对于多行公式块来说，只有改写成单行的形式才能正常显示，这个我得思考下后续怎么搞定它
临时的解决方案如下：
```
<div>行间公式：<br><anki-mathjax>\begin{aligned} &amp;{{c1::{\color{#C72929}{\|f+g\|_p = \left( \int_E |f+g|^p \, dx \right)^{1/p} } } }} \\ &amp;= \left( \int_E |f|^p \, dx + \int_E |g|^p \, dx \right)^{1/p} \\ &amp;\leq \|f\|_p + \|g\|_p \end{aligned}</anki-mathjax><br><br></div><div>行内公式：<br><anki-mathjax block="true">f(x)={{c1::{\color{#C72929}{ab{a\over b}2132313 } } }}</anki-mathjax><br></div>
```
![ClozeAdv_Mathjax_block_issues](https://github.com/user-attachments/assets/9dad2911-5602-4b6e-9e26-6191b215536d)

另外对于新版本的Anki和AnkiDroid的适配需要等我更新下

**Comment by ruin1990** [comment]
当前版本上，可能对于Mathjax的特殊处理都得参考上述两点

**Comment by ruin1990** [comment]
另外还可以参考[ClozeAdv Mathjax 特殊处理指南](https://github.com/ruin1990/AnkiTemplate/tree/main/ClozeAdv#mathjax-bugs)

**Comment by ruin1990** [comment]
相关建议已经添加到readme.md文档里，这个issue先关闭了。多行的兼容性以后研究一下再开启，暂时先不修复。期待有大佬PR

**Comment by EchoingWhispers** [comment]
好用心！谢谢您的回复哈
