### ISSUE TITLE
在AnkiDroid中无法正确显示卡片对应的答案

### ISSUE THREAD

**Issue by danghieu2gia1** [ruin1990/AnkiTemplate#8]
大佬您好，很感谢您的这个模板，我这两年一直在用，前阵子AnkiDroid更新到2.18.4之后除了一些bug。如图所示图1中蓝色部分也就是这个笔记的第二个卡片（{{c2::}}）显示的答案其实是我第一张卡片的内容（{{c1::}}），我自己不懂写代码，不知道如何修复这个bug。非常期待您的建议或任何修复的指导，谢谢。
![图1](https://github.com/user-attachments/assets/92d70017-5610-40c7-8c17-6a838e7fd2fe)
![图2](https://github.com/user-attachments/assets/ed7b6731-9b52-4fd5-8a4d-8283d12daa53)

**Comment by danghieu2gia1** [comment]
[只显示c1的答案.zip](https://github.com/user-attachments/files/16735584/c1.zip)
您好，我在ankiweb上看到别人有跟我一样的问题，但是没有提供卡牌给您分析，这个是我出问题的卡牌，在您的模板中添加了一些字段，做了一些修改，但是没有改动改码部分。希望您能帮忙修复一下这个问题。

**Comment by ruin1990** [comment]
稍等哈，我这个月有空的时候看一下这个问题，终于遇到个提供问题卡组的了，感谢感谢
粗略看了一下，问题应该出在我判断这是第几张卡片的问题上，我的卡组都还在旧版，得全部升级迁移到最新版下复现下。
我的pc版可能也有这个问题

**Comment by ruin1990** [comment]
应该找到原因了，初步测试ok，不过另外一个issue里的mathjax问题我还得解决下

**Comment by danghieu2gia1** [comment]
2.16.2没问题，2.18就不行了

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: ruin1990 ***@***.***>
发送时间: Tuesday, September 10, 2024 11:08:57 AM
收件人: ruin1990/AnkiTemplate ***@***.***>
抄送: Emmmm ***@***.***>; Author ***@***.***>
主题: Re: [ruin1990/AnkiTemplate] 在AnkiDroid中无法正确显示卡片对应的答案 (Issue #8)


另外问下你之前能用的ankidroid版本是多少，我发现是anki预处理的机制变了，我原先是判断哪个字段被改为cloze了，现在好像不行了，恐怕得另想他法

―

**Comment by ruin1990** [comment]
https://github.com/ruin1990/AnkiTemplate/blob/main/ClozeAdv/AnkiTemplate_ClozeAdv.apkg
测试测试，front.html也更新了你试试更新到你的模版里，我稍微验证了下ok。
期待你的反馈哈，我先更新到ankiweb和release里，有问题再改好了

**Comment by danghieu2gia1** [comment]
用最新版本的ankidroid吗？

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: ruin1990 ***@***.***>
发送时间: Wednesday, September 11, 2024 3:49:23 PM
收件人: ruin1990/AnkiTemplate ***@***.***>
抄送: Emmmm ***@***.***>; Author ***@***.***>
主题: Re: [ruin1990/AnkiTemplate] 在AnkiDroid中无法正确显示卡片对应的答案 (Issue #8)


https://github.com/ruin1990/AnkiTemplate/blob/main/ClozeAdv/AnkiTemplate_ClozeAdv.apkg
测试测试，front.html也更新了你试试更新到你的模版里，我稍微验证了下ok。
期待你的反馈哈，OK以后我再更新到ankiweb和release里

―

**Comment by ruin1990** [comment]
对的，我弄了个小号测试了下我修改后的模版是ok的，你可能需要把我的模版copy到你的模版里一下，我直接测了下可以用。直接用的2.18.4和2.19beta1的测试了下。PC测试了24.06.3
Issue 先关闭了如果有，你再reopen

**Comment by danghieu2gia1** [comment]
刚刚将您的代码复制到我的模板里，在AnkiDroid 2.18.4中显示顺序是正常的，谢谢！

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: ruin1990 ***@***.***>
发送时间: Thursday, September 12, 2024 2:29:53 PM
收件人: ruin1990/AnkiTemplate ***@***.***>
抄送: Emmmm ***@***.***>; Author ***@***.***>
主题: Re: [ruin1990/AnkiTemplate] 在AnkiDroid中无法正确显示卡片对应的答案 (Issue #8)


对的

―

**Comment by ruin1990** [comment]
OK，不客气哈，解决了就好，趁此机会我也把我PC和Android的版本升级到了最新版。另外我这次更新以后网页版也支持了
