### ISSUE TITLE
有表格时候，预览到表格挖空会卡死

### ISSUE THREAD

**Issue by 512-dhl** [ruin1990/AnkiTemplate#9]
有表格文本挖空时候时候，预览到表格挖空会卡死

**Comment by ruin1990** [comment]
您好，我这里很多卡组也用到了表格，并没有您说的这种情况，提供完整能复现问题的demo 卡组apkg文件，这里可以有空的时候看看。@512-dhl
最好能说明下在哪个客户端能复现这种情况，一般优先考虑升级客户端到最新版。
另外我有发现Android系统如果自带的webview版本太低(我的一台设备是75)，啥卡片预览都会卡死
最后，欢迎PR

**Comment by 512-dhl** [comment]
现在没这种情况了，感谢模板




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ruin1990/AnkiTemplate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月16日(星期三) 晚上6:55
***@***.***&gt;;
抄送:&nbsp;"Edward ***@***.******@***.***&gt;;
主题:&nbsp;Re: [ruin1990/AnkiTemplate] 有表格时候，预览到表格挖空会卡死 (Issue #9)





 
您好，我这里很多卡组也用到了表格，并没有您说的这种情况，提供完整能复现问题的demo ***@***.***
 另外，欢迎PR

**Comment by ruin1990** [comment]
好的，问题解决就好，如果方便分享解决的过程就更好了，方便以后遇到类似问题的朋友能参考
